import os
import subprocess
import tempfile
import logging
from typing import Dict

logger = logging.getLogger(__name__)

MAX_FILE_SIZE = 1 * 1024 * 1024  # 1 MB

IGNORE_FILES = {
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Gemfile.lock",
    "poetry.lock",
    "Cargo.lock",
    "go.sum",
    "composer.lock",
    "mix.lock",
    "pixi.lock"
}

def is_binary(file_path: str) -> bool:
    """
    Check if a file is binary by reading the first chunk and looking for null bytes.
    """
    try:
        with open(file_path, 'rb') as f:
            chunk = f.read(1024)
            if b'\0' in chunk:
                return True
            return False
    except Exception:
        return True

def ingest_repo_files(repo_url: str) -> Dict[str, str]:
    """
    Clones a repository into a temporary directory, reads its tracked files,
    and returns a dictionary mapping file paths (relative to the repo root) to their contents.
    Skips binary files, large files, and files that are not UTF-8 encoded.
    """
    files_content = {}

    with tempfile.TemporaryDirectory() as temp_dir:
        # Clone the repository
        try:
            logger.info(f"Cloning repository {repo_url} into {temp_dir}...")
            subprocess.run(
                ["git", "clone", "--depth", "1", "--", repo_url, temp_dir],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to clone repository: {e.stderr.decode('utf-8')}")
            raise RuntimeError(f"Failed to clone repository {repo_url}") from e

        # Get list of tracked files using git ls-files
        try:
            result = subprocess.run(
                ["git", "-C", temp_dir, "ls-files", "-z"],
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )
            tracked_files = [f for f in result.stdout.split('\0') if f]
        except subprocess.CalledProcessError as e:
            logger.error(f"Failed to list files: {e.stderr}")
            raise RuntimeError(f"Failed to list files in repository {repo_url}") from e

        for file_path in tracked_files:
            full_path = os.path.join(temp_dir, file_path)
            file_name = os.path.basename(file_path)

            # Skip lock files and common large autogenerated files
            if file_name in IGNORE_FILES or file_name.endswith(".lock"):
                logger.debug(f"Skipping {file_path}: Lock file")
                continue

            # Skip if it's not a file (e.g., symlink to a directory)
            if not os.path.isfile(full_path):
                continue

            # Check file size
            if os.path.getsize(full_path) > MAX_FILE_SIZE:
                logger.debug(f"Skipping {file_path}: File too large")
                continue

            # Check if binary
            if is_binary(full_path):
                logger.debug(f"Skipping {file_path}: Binary file")
                continue

            # Try to read the file as UTF-8
            try:
                with open(full_path, 'r', encoding='utf-8') as f:
                    content = f.read()
                    files_content[file_path] = content
            except UnicodeDecodeError:
                logger.debug(f"Skipping {file_path}: Not a UTF-8 file")
            except Exception as e:
                logger.debug(f"Skipping {file_path}: Error reading file - {e}")

    return files_content
